name: Question
description: Ask a question about usage or implementation
title: "[Question]: "
labels: ["question"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Have a question? We're here to help!

        For general discussions, please consider using [GitHub Discussions](https://github.com/GerdsenAI/GerdsenAI-Depth-Anything-3-ROS2-Wrapper/discussions).

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: How do I...
    validations:
      required: true

  - type: dropdown
    id: topic
    attributes:
      label: Topic Area
      description: What is your question about?
      options:
        - Installation and setup
        - Camera integration
        - Docker deployment
        - Performance tuning
        - Model selection
        - Multi-camera setup
        - ROS2 topics and parameters
        - Error troubleshooting
        - Best practices
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide context about what you're trying to accomplish
      placeholder: |
        I am trying to...
        My setup includes...
    validations:
      required: false

  - type: textarea
    id: attempted
    attributes:
      label: What Have You Tried?
      description: What have you already attempted?
      placeholder: |
        I tried...
        I looked at...
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment Details (if relevant)
      description: Provide system details if relevant to your question
      placeholder: |
        OS: Ubuntu 22.04
        ROS2: Humble
        Device: CUDA/CPU
        Camera: ZED 2i
      render: markdown
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify before submitting
      options:
        - label: I have searched existing issues and discussions
          required: true
        - label: I have checked the documentation and README
          required: true
